### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by azze-r** [Kwpolska/think#1]
i run on manjaro linux 32 bits
after installation and configuration, i try    

```
 [boblinux@bobz ~]$ think sleep 120

 Traceback (most recent call last):
   File "/usr/bin/think", line 11, in <module>
     sys.exit(main())
   File "/usr/lib/python2.7/site-packages/think.py", line 92, in main
     stdout=DEVNULL, stderr=DEVNULL)
   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
     errread, errwrite)
   File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
     raise child_exception
 OSError: [Errno 2] No such file or directory
```

my configuration file is /home/boblinux/.config/think.conf and contains

```
 [Think]
 command = play
 file = /home/boblinux/audio/coran 001.mp3
 behavior = wait
```

**Comment by Kwpolska** [comment]
Do you have `play` (from the `sox` package) installed?

## 

Chris Warrick https://chriswarrick.com

**Comment by azze-r** [comment]
How can i know? sorry i'm yet a noob in linux's world
thanks

**Comment by Kwpolska** [comment]
```
sudo apt-get install sox
```

Does `think` work after you do this?

**Comment by azze-r** [comment]
In manjaro linux (like archlinux) the command is

```
 sudo pacman -S sox
```

I have no error, but i don't hear nothing =/ 

When i interrupt the process i have 

```
 CTraceback (most recent call last):
   File "/usr/bin/think", line 11, in <module>
     sys.exit(main())
   File "/usr/lib/python2.7/site-packages/think.py", line 93, in main
     time.sleep(0.1)
```

**Comment by azze-r** [comment]
I don't think probleme is due to sox now  ^^

**Comment by Kwpolska** [comment]
1. Sorry, thought you were on Mint.  I’m an Archer myself.
2. The output on interruption is normal.  I could get rid of it, but it’s not a bug.

**Comment by Kwpolska** [comment]
^C output suppressed in think v0.1.2

also, if you can access and use the AUR in Manjaro, use that to install.

**Comment by azze-r** [comment]
Hum...whait, i'm trying to understand ;)

So, what do i have to download with AUR ?
You're talking about downlowading sox ? think ?

It is not a problem about output, the problem is that i don't hear nothing when i use think.
Maybe you can print what the users is supposed to hear ? because there is no output when using think, so we can't know what the problem.

For exemple, you can print 

```
 You're listening /home/audio/zz.mp3 
```

But now, i can't see if the application arrive to read my file or not.

Do you understand what i mean?

**Comment by Kwpolska** [comment]
1. download `think` from the AUR if you can, or just use pip if you can’t.
2. this would break the user experience and be generally useless.  With this config file:
   
   ``` ini
   [Think]
   command = play
   file = /home/boblinux/audio/coran 001.mp3
   behavior = wait
   ```
   
   think will execute the command `play "/home/boblinux/audio/coran 001.mp3"` — this is all it does
